### ISSUE TITLE
Source blocks

### ISSUE THREAD

**Issue by bmaland** [bdewey/org-ruby#1]
Source blocks (#BEGIN_SRC $type) are currently wrapped in &lt;p&gt; tags, but &lt;pre class="src src-$type"&gt; would be more appropriate, and in line with what org-mode HTML export does.

**Comment by bdewey** [comment]
I just pushed version 0.5.1 that _mostly_ addresses this. Source blocks now get tagged _pre_ with class _src_, but no specific class for the language.

**Comment by bmaland** [comment]
Cool, thanks. I'll give it a try later :)
