### ISSUE TITLE
Bump gem version

### ISSUE THREAD

**Issue by chaffeqa** [bdewey/org-ruby#16]
Could you bump the gem version so that it includes your Ruby 1.9 utf8 support just submitted? 

Would be much obliged :)

**Comment by pal** [comment]
+1!

**Comment by pwnall** [comment]
+1

**Comment by wallyqs** [comment]
This took a while, but the version with this fix is now on rubygems.

**Comment by chaffeqa** [comment]
You guys rock!

**Comment by pwnall** [comment]
Thank you very much!
