### ISSUE TITLE
invalid multibyte char (US-ASCII)

### ISSUE THREAD

**Issue by pmq20** [bdewey/org-ruby#17]
/usr/local/lib/ruby/gems/1.9.1/gems/RedCloth-4.2.8/lib/redcloth.rb:10: Use RbConfig instead of obsolete and deprecated Config.
/usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require': /usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby/textile_symbol_replace.rb:5: invalid multibyte char (US-ASCII) (SyntaxError)
/usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby/textile_symbol_replace.rb:5: invalid multibyte char (US-ASCII)
/usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby/textile_symbol_replace.rb:5: syntax error, unexpected $end, expecting ')'
    str.gsub!(/\\Agrave((\{\})|(\s|$))/, "À\\3")
                                            ^
    from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in`block in require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:640:in`new_constants_in'
    from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby.rb:43:in `block in require_all_libs_relative_to'
    from /usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby.rb:43:in`each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby.rb:43:in `require_all_libs_relative_to'
    from /usr/local/lib/ruby/gems/1.9.1/gems/org-ruby-0.6.0/lib/org-ruby.rb:48:in`<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler/runtime.rb:68:in`block (2 levels) in require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler/runtime.rb:66:in`block in require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler/runtime.rb:55:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.0.21/lib/bundler.rb:122:in `require'
    from /root/t2ku/config/application.rb:8:in`<top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.1.3/lib/rails/commands.rb:52:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.1.3/lib/rails/commands.rb:52:in`block in <top (required)>'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.1.3/lib/rails/commands.rb:49:in `tap'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.1.3/lib/rails/commands.rb:49:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by pal** [comment]
This is fixed in 1704057bfe171c52d151e6b1c44c156a9be656a0, can you try if this fixes your problem?

Now, if only this came as part of a public release soon... :)

**Comment by grosser** [comment]
please release...I also need this

**Comment by piotreq** [comment]
+1

**Comment by pmq20** [comment]
actually just use :git => 'git://github.com/bdewey/org-ruby.git' in your Gemfile and it's working fine

**Comment by wallyqs** [comment]
I have included this in this version of the gem for now: https://rubygems.org/gems/wallyqs-org-ruby

**Comment by trevor** [comment]
:+1:

**Comment by bootstraponline** [comment]
+1 for release. This is currently breaking Gollum.

**Comment by atmos** [comment]
A release would be cool.  Gemfile is a decent fix for apps but other gems that require this fixup need a release you can install from rubygems.

**Comment by wallyqs** [comment]
Good news! @bdewey just shared ownership of the gem :) 
I pushed a version of the gem where this is fixed => https://rubygems.org/gems/org-ruby/versions/0.6.2

**Comment by bootstraponline** [comment]
Thanks for making a new gem release.

**Comment by trevor** [comment]
thanks @wallyqs

**Comment by atmos** [comment]
:heart:
