### ISSUE TITLE
InlineExampleRegexp is slightly incorrect

### ISSUE THREAD

**Issue by jacius** [bdewey/org-ruby#21]
In the org-mode guide [section on literal examples](http://orgmode.org/guide/Literal-examples.html), it says (emphasis mine):

> For simplicity when using small examples, you can also start the example lines with a colon **followed by a space**. There may also be additional whitespace before the colon
> 
> <pre>      Here is an example
>         : Some example from a text file.</pre>

Currently, org-ruby doesn't check whether there is a space after the colon. This can cause some things to be rendered incorrectly. For example, if you are writing about Ruby `:symbols` or Common Lisp `:keywords` and your paragraph wraps so that the `:` is at the start of a line:

```
I really love to write about
:symbols. They sure are the
best things in the world!
```

it ends up looking like this:

<blockquote>
I really love to write about
<pre>symbols. They sure are the</pre>
best things in the world!
</blockquote>

when I would expect an uninterrupted normal paragraph.

So, to match the behavior described in the guide, I think InlineExampleRegexp (in lib/org-ruby/line.rb) should be changed from this:

``` ruby
    InlineExampleRegexp = /^\s*:/
```

... to something like this (untested):

``` ruby
    InlineExampleRegexp = /^\s*: /
```

**Comment by wallyqs** [comment]
Thanks for the hint! There was a very old issue regarding this. It should be fixed now.

**Comment by akicho8** [comment]
It appears to have collapsed to was displayed beautifully in the old days.
- https://github.com/akicho8/game_ai#%E3%82%B9%E3%83%86%E3%83%BC%E3%83%88%E3%83%99%E3%83%BC%E3%82%B9ai
- https://github.com/akicho8/design_pattern#active-object---%E9%9D%9E%E5%90%8C%E6%9C%9F%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%82%92%E5%8F%97%E3%81%91%E5%8F%96%E3%82%8B

Line of only colon char then export will also be subject to the pre from org-mode that is attached to emacs.
I'm having problems.
How do I use.

**Comment by vonavi** [comment]
Dear @akicho8,

Please, open a new issue with a simple example `example.org` and show there the actual output and the expected one. We support the org-ruby gem, please check it as follows:

```
gem install org-ruby
org-ruby example.org
```

and paste the output.

Best regards, Vladimir.

**Comment by wallyqs** [comment]
@akicho8 -san, according to the Org-mode spec you need to use a single colon after ':' for this to work.

http://orgmode.org/manual/Literal-examples.html
"you can also start the example lines with a colon followed by a space"

Org-modeのスペックによるとliteral exampleを使う時に「：」の後にシングルスペースが必要になります。そうじゃないと #6 を対応出来なくなる...
例：https://github.com/wallyqs/game_ai/blob/145160be9caa3321fe78d2813cb0d1edb8293a7b/README.org

Hope this helps!

**Comment by akicho8** [comment]
This is unavoidable if determined by the specification of org-mode.
I going to replace: ":\n" to: ": \n".
Thank you for fast response.

**Comment by akicho8** [comment]
I tried as follows. Was easier to use.

```
(defun org-mode-colon-only-line-as-example ()
  (interactive)
  (when (eq major-mode 'org-mode)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward (regexp-quote ":\n") nil t)
        (replace-match ": \n" nil nil)))))

(add-hook 'after-save-hook 'org-mode-colon-only-line-as-example)
```

**Comment by wallyqs** [comment]
:thumbsup:
