### ISSUE TITLE
Org and Pygments use different language identifiers

### ISSUE THREAD

**Issue by hanjianwei** [bdewey/org-ruby#28]
Difference between [Org](http://orgmode.org/worg/org-contrib/babel/languages.html) and [Pygments](http://pygments.org/docs/lexers/) leads to some errors. For example:

```
#+begin_src emacs-lisp
    (global-visual-line-mode)
#+end_src
```

Pygments will complain:

> ClassNotFound: no lexer for alias 'emacs' found

It's ok if I change `emacs-lisp` to `scheme`.

**Comment by wallyqs** [comment]
Thanks for reporting this. The programming language name should be normalized so that it matches the way we use it in org-mode, I will patch this soon.

**Comment by wallyqs** [comment]
I gave a quick look both of the lists, and it seems that for most cases Pygments and Org use similar language identifiers overall, but Pygments does not support directly emacs-lisp, common-lisp and other lisp dialects. 
In the meantime, I will make `emacs-lisp` and `common-lisp` identifiers default to use the scheme lexer from Pygments.
Also one question, how did you get the `ClassNotFound` error? When I test using a non-supported lexer from Pygments, it defaults on using the 'text' lexer for the block. 
https://github.com/bdewey/org-ruby/blob/master/lib/org-ruby/html_output_buffer.rb#L117

**Comment by hanjianwei** [comment]
I can reproduce the error just by the following command:

``` sh
org-ruby -d test.org
```

test.org is a simple file you can find in [this gist](https://raw.github.com/gist/3148062/393be2be4f4be15fbcfc27993efeff1e85d80e76/test.org).

See the error message [here](https://gist.github.com/3148089)

Thanks for your help!

Edit:  the error message may be misleading. Sometimes I can get correct result. I'll check the file again and report later.

**Comment by wallyqs** [comment]
Ok! I added a special case for lisp dialects so that they use the scheme parser from Pygments: https://github.com/bdewey/org-ruby/commit/180d995bd7ae3b8dab99bcf0bcafd9455bfc33fc

**Comment by hanjianwei** [comment]
Thanks a lot!
