### ISSUE TITLE
Lists using '*' bullets are not recognized

### ISSUE THREAD

**Issue by pinterface** [bdewey/org-ruby#29]
Unordered lists such as

```
  * One
  * Two
  * Three
```

are not recognized as such.

Ditto for definition lists using the same convention.

```
  * One :: The first number.
  * Two :: The second number.
```

Can be fixed by changing `/^\s*(-|\+)` to `/^\s*(-|\+|\s+[*])` in lib/org-ruby/line.rb for both items.

**Comment by wallyqs** [comment]
Hope this helps :)
