### ISSUE TITLE
Definition Lists are different from org-mode in some cases

### ISSUE THREAD

**Issue by pinterface** [bdewey/org-ruby#30]
Given an org-mode file like so,

```
* Definition List Items

 + Key :: Value (k1)
 - K::e::y :: Value (k2)
 + Key ::
   Value (k3)
 + Key :: Value :: Still value (k4)
 - Key ::MoreKey :: Value (k5)
 - Key:: MoreKey :: Value (k6)
 - :: Key :: Value (k7)

* Not Definition List Items

 - Key:: Value (n1)
 - Key ::Value (n2)
 - Key::Value (n3)
 - Key::
   Value (n4)
 + Key
   :: Value (n5)
```

org-ruby agrees with org-mode\* (version 7.8.03, anyway) only on the '+' items; all of the '-' items are handled differently (k2, k5, k6, and k7 disagree on what constitutes the term; n1-4 disagree on whether they're even definitions).

These differences can be reduced by changing the regexp to something more suitable, like `/^\s*(-|\+|\s+[*])\s*(.*?)\s+::(?:\s+|$)/`.

However, even using an improved regex, org-ruby and org-mode continue to disagree on what constitutes the definition term in k2, k5, k6, and k7.  This appears to be because html_output_buffer.rb is splitting on the the first instance of '::' to determine the key.

\* Well, the buffer-highlighting, anyway.  org-mode's HTML export spits out k4 using a term of "Key :: Value", rather than "Key" as highlighted in the buffer, so even org-mode itself is not entirely self-consistent on these, which suggests some may be more emergent properties than intentional decisions.

**Comment by wallyqs** [comment]
Thanks for the write up, I will fix `html_output_buffer` definition list output to consider these cases (pull requests are welcome by the way :) )

**Comment by pinterface** [comment]
On 2012.08.27 19:17, Waldemar Quevedo Salinas wrote:

> (pull requests are welcome by the way :) )

I don't actually know any Ruby, but I'll keep that in mind in the event 
I figure out enough of the Ruby ecosystem to adequately test any such 
patches. :)
