### ISSUE TITLE
Incorrect indention for structural elements

### ISSUE THREAD

**Issue by hanjianwei** [bdewey/org-ruby#31]
For the following examples the space before `(+ 3 5)` and `This is an example.` will be stripped when I export them using Emacs (`M-x org-export-as-html`). But org-ruby will keep the spaces. Is this a bug or undefined behavior?

```
  #+begin_src emacs-lisp
    (+ 3 5)
  #+end_src

#+begin_example
  This is an example.
#+end_example
```

Thanks!

**Comment by wallyqs** [comment]
I will consider this as a bug, it makes sense to consider the initial indentation from #+begin_src as the the correct indentation for the whole code block.
