### ISSUE TITLE
hostname-only links are corrupted

### ISSUE THREAD

**Issue by tarsius** [bdewey/org-ruby#4]
This link does not work: `[[http://example.com]]`, it's interpreted as `[[http://example.html]]`.

This works however: `[[http://example.com/index.html]]`.

This applies to the version used for the new github wikis.

**Comment by punchagan** [comment]
This bug seems to have been fixed.

**Comment by bdewey** [comment]
Agree. The test case "inline-formatting" shows this works in the current version of the gem.
