### ISSUE TITLE
0.8.0 & 0.8.1 break gollum's tests

### ISSUE THREAD

**Issue by bootstraponline** [bdewey/org-ruby#45]
I upgraded gollum from org-ruby 0.7.2 and now there are [four test failures](https://travis-ci.org/github/gollum/jobs/4915199). Are these issues in org-ruby? For now I've [reverted back to 0.7.2](https://github.com/github/gollum/commit/3ee6d22727ae155d2d5e8c30b25ee1fe5651471b).

**Comment by vonavi** [comment]
Hey!
Thank you for the notice. It's not a bug. The difference is that org-ruby 0.8.\* does not assign class `title` to the first paragraph of org-mode file, this class is preserved for lines with `#+TITLE:`. You can send a pull request to gollum removing `class="title"` from expected results. See lines [728](https://github.com/github/gollum/blob/master/test/test_markup.rb#L728), [734](https://github.com/github/gollum/blob/master/test/test_markup.rb#L734), [740](https://github.com/github/gollum/blob/master/test/test_markup.rb#L740), [746](https://github.com/github/gollum/blob/master/test/test_markup.rb#L746) in [test_markup.rb](https://github.com/github/gollum/blob/master/test/test_markup.rb).

Best regards,
Vladimir.

**Comment by bootstraponline** [comment]
Thanks for letting me know.

**Comment by bootstraponline** [comment]
It's now [fixed in gollum](https://github.com/github/gollum/commit/78f5df5e560a4af9417b08bdf2f583228148858c).
