### ISSUE TITLE
Leading level1 header not displayed, text before first header ignored

### ISSUE THREAD

**Issue by tarsius** [bdewey/org-ruby#5]
If a file starts with a level1 heading that heading is not displayed, instead the file name is used:

```
* level1 is invisible
content
```

This would be okay but at the same time text before the first heading is hidden also:

```
this won't be visible
* whatever level
```

It's possible to work around this:

```
* i make the following text visible
text that belongs under the page-name-header
* more stuff
```

Again this was observed using the new github wikis.

**Comment by punchagan** [comment]
This bug seems to be fixed, too. Can be closed.

**Comment by bdewey** [comment]
Make sure you don't have the "skip" option set to "t" somewhere in the beginning of your file, like this line:

#+OPTIONS:   TeX:t LaTeX:nil skip:t d:nil todo:t pri:nil tags:not-in-toc

...which is boilerplate that gets inserted in my org files, so perhaps you insert it in yours. Per the org-manual:

http://orgmode.org/manual/Export-options.html#Export-options

"skip:t" means that all text before the first heading should get skipped on export. org-ruby honors that export setting.
