### ISSUE TITLE
treating lines starting with a comma prepended in org-mode literal block

### ISSUE THREAD

**Issue by msnoigrs** [bdewey/org-ruby#50]
In org-mode literal blocks i.e. #+BEGIN_EXAMPLE ... #+END_EXAMPLE block and #+BEGIN_SRC ... #+END_SRC block, please don't export a prepended comma.

http://orgmode.org/manual/Literal-examples.html:

"[4] Upon exit, lines starting with ‘*’, ‘,*’, ‘#+’ and ‘,#+’ will get a comma prepended, to keep them from being interpreted by Org as outline nodes or special syntax. These commas will be stripped for editing with C-c ', and also for export."

**Comment by wallyqs** [comment]
I see, I have a fix for this coming up. I will include it in 0.8.2 version. Thanks :)
