### ISSUE TITLE
Add support for link abbreviations (file only)

### ISSUE THREAD

**Issue by mrvdb** [bdewey/org-ruby#52]
org-mode has a feature called link abbreviations:

http://orgmode.org/manual/Link-abbreviations.html#Link-abbreviations

The file-specific form of them looks like:
# +LINK: example http://example.com/something

The defined link can be referenced in the text using square brackets:

  [[example][Text that will get linked]]

I'm using org-ruby in combination with jekyll and for blog articles having a set of links organized together instead of scattered through the text would make the editting process quite a bit more enjoyable.

**Comment by wallyqs** [comment]
Hi, this was just fixed at #53 
I will release a new version of the gem this week so that this can be used in Jekyll.

**Comment by mrvdb** [comment]
That was fast! Cool.
