### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by funal125** [bdewey/org-ruby#55]
Would you support markdown ?

**Comment by wallyqs** [comment]
Do you mean something like a markdown exporter?

**Comment by funal125** [comment]
Yes, you are right. I think it will be very cool.

**Comment by wallyqs** [comment]
I just merged to master some preliminar support for `markdown` exporter. I haven't gotten around implementing footnotes export yet and there are still some incompatibilities between Org and Markdown syntax, though I think it is good enough to share already.

You can try it in its current status with:

```
org-ruby <file> --translate markdown 
```

Can you try? I will include it on a release once receiving some feedback (also PRs are welcome!)

**Comment by funal125** [comment]
Ok, i will try it. Thanks a lot.

**Comment by wallyqs** [comment]
I released this in version 0.8.3 of the gem. :) Hope this helps.
