### ISSUE TITLE
`*bold*` becomes `@<b>bold@</b>` in a description list

### ISSUE THREAD

**Issue by vermiculus** [bdewey/org-ruby#57]
See [a short document of mine](https://github.com/vermiculus/gui4l3/blob/584008399f79e76eaf324947c3874f5257b050b7/latex3.org) for an example, but basically what we have is

``` ruby
require 'org-ruby'
Orgmode::Parser.new("- description :: *list*").to_html
```

``` html
<dl>
  <dt>description</dt><dd>@<b>list@</b></dd>
</dl>
```

**Comment by wallyqs** [comment]
Just pushed a patch that would fix this in master, there seems to be no regressions so I will release it soon. Thanks for the report.
