### ISSUE TITLE
org mode #+begin_src clojure tag doesn't render ":" properly in HTML

### ISSUE THREAD

**Issue by mchampine** [bdewey/org-ruby#6]
org file to HTML rendering on github drops leading ":" in begin_src clojure blocks.

for example, if you try to include a project.clj in a README, it will display with the leading ":" stripped.

**Comment by bdewey** [comment]
I'm confused by what leading colon you're talking about. Can you provide an example?

**Comment by mchampine** [comment]
I was just referring to normal clojure syntax, where the colon ":" is used to begin clojure keynames.  A code example would be 

(def m {:a "x" :b "y" :c "z" :d "w"})

I don't remember exactly, but I think if the very first non-whitespace character on a clojure source code line is the ":" it was dropped.

**Comment by bdewey** [comment]
Got it. A colon at the beginning of a line is also syntax for starting an
example... which _is_ superfluous if it's source code. I'll look into a fix.
Thanks.
