### ISSUE TITLE
Org file parsing fails on #+OPTIONS line

### ISSUE THREAD

**Issue by spacebat** [bdewey/org-ruby#62]
I was using gitlab and ran into a 500 server error when trying to view a repo with a `README.org` file that contained the output of `org-export-insert-default-template`. In particular the following line seemed to be a problem:

```
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
```

The error was:

```
Unexpected option: "LOGBOOK"
```

I worked around it by removing all `#+OPTIONS` lines. The gitlab guys suggested I open the issue here.

**Comment by Razer6** [comment]
The problem is because of the option `(not "LOGBOOK")`. Whitespace fails parsing the option

**Comment by wallyqs** [comment]
Thanks for the report, taking a look.
By the way the project has moved to here: https://github.com/wallyqs/org-ruby

**Comment by wallyqs** [comment]
Just pushed a version of the gem (0.9.8) were this is fixed. Cheers.
