### ISSUE TITLE
Change "_word_" to generic span "underline" rather than in-line text-decoration.

### ISSUE THREAD

**Issue by mashdot** [bdewey/org-ruby#64]
I just spotted than when I use:

`_word_`

It is parsed to:

`<span style="text-decoration:underline;">word</span>`

I am wanting to use underline as a means to highlight text in a document. Unfortunately [`<mark>` is not supported in org-mode](http://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00106.html), and so I would like to request the following output:

`<span style="underline">word</span>`

This would allow us to define and manage `underline` in CSS directly, which I feel is more useful then in-line styling.

Thoughts?

Note: Originally posted to: https://github.com/eggcaker/jekyll-org/issues/7

**Comment by vonavi** [comment]
The upstream was moved to https://github.com/wallyqs/org-ruby Please, reopen the issue there. My apologies for the confusion.

**Comment by wallyqs** [comment]
In org-ruby you may be able to workaround by overriding the markup: https://github.com/wallyqs/org-ruby#html-emphasis
Please reopen on the other repo in case you want to follow up this usage. Thanks.
