### ISSUE TITLE
Incorrect handling of nested code tags

### ISSUE THREAD

**Issue by perusio** [bdewey/org-ruby#7]
Thank you for org-ruby. I've reported this issue to github that pointed to org-ruby.

Here's the issue: http://support.github.com/discussions/repos/4086-org-mode-markup-handling-half-broken-and-no-support-for-org-babel-code-blocks

**Comment by ghost** [comment]
I solved this by capitalizing the tag #+begin_src and #+end_src.
Maybe you can change the function, that org-ruby would be non case sensitive in this matter. 
For now this can be a bit confusing for other users of org-files.

**Comment by bdewey** [comment]
Sorry for the delay... I've been on hiatus from org_ruby. 

One of the problems handling org mode files is there isn't a real "spec" -- just what's implemented by the emacs lisp. And there are also a million features that _I_ never use, like source blocks. Anyway, that's my excuse... I didn't know this was supposed to be case insensitive! It's a simple enough fix to make, though, so I'm working on the change now.

**Comment by punchagan** [comment]
This has been fixed. The issue can be closed.

**Comment by punchagan** [comment]
49983d31fd2dbbc4f593 fixes this issue.
