### ISSUE TITLE
Add a support for link with tag

### ISSUE THREAD

**Issue by Vonfry** [bdewey/org-ruby#71]
In org, we can use `#+link: tagname url` with `[[tagname][description]`.

Example:
```
[[google:org][Org]]

#+link: google https://google.com/search?q=%s
```
Would you like add this in the project?

**Comment by vonavi** [comment]
Hello @VonFry ! There is no such link format at http://orgmode.org/guide/Link-format.html#Link-format . Please give me a document describing this feature.

**Comment by Vonfry** [comment]
http://orgmode.org/org.html#Link-abbreviations

**Comment by Vonfry** [comment]
Sorry, I have a wrong understanding for it......
