### ISSUE TITLE
Add support for footnotes

### ISSUE THREAD

**Issue by bzg** [bdewey/org-ruby#72]
**Thanks** a lot for maintaining org-ruby!

I use org-ruby a lot with jekyll and I often wish it could support org footnotes.  At least the most common schema for footnotes, i.e. `[fn:1] A footnote`.

What is need for someone to start hacking on this?

What is the main difficulty?

Thanks!

**Comment by pierre-lecocq** [comment]
Salut Batien !

Footnotes are already supported as far as I know.

Here is an example: https://raw.githubusercontent.com/bdewey/org-ruby/master/spec/html_examples/footnotes.org

If there is something missing, can you give us more details here, please?

Thanks in advance,

Pierre

**Comment by bzg** [comment]
Hi @pierre-lecocq !

thanks for replying - so maybe this is more an issue for https://github.com/eggcaker/jekyll-org: the jekyll plugin converts org files correctly, except for footnotes.

Has anyone been able to setup a jekyll blog with org and footnotes?

**Comment by pierre-lecocq** [comment]
May you just test one thing against one of your org file, please?

`org-ruby your_file.org --translate html`

and see if the footnotes are here?

I will test with jekyll as soon as I can.

**Comment by bzg** [comment]
Okay, I tested and it seems I just forgot to add `#+options: f:t` - things are working as expected, sorry for the noise and thanks for the feedback!

**Comment by pierre-lecocq** [comment]
Thank you so much for maintaining org-mode, by the way :)

A bientot, Bastien!
