### ISSUE TITLE
Verbatim in links, and ==verbatim==

### ISSUE THREAD

**Issue by kaushalmodi** [bdewey/org-ruby#76]
Hello,

I recently learned that this repo is used by GitHub to render Org markup. 

I have hit few cases where GitHub doesn't render the Org markup correctly, especially these 2 verbatim cases:

## ==verbatim==

Example: https://github.com/kaushalmodi/ox-hugo/blob/master/README.org#formatting

See ==monospace== in that table. I expected to see =monospace= rendered in monospace. Org mode does so natively in Emacs.

## Verbatim text in links
The rendering of an Org link like below:

    [[https://www.example.com][=description=]]

should be equivalent to that of:

    [`description`](https://www.example.com)

But at the moment the verbatim markup characters around 'description' in that link stay unrendered.
You can see examples of this issue too in the same Formatting section: https://github.com/kaushalmodi/ox-hugo/blob/master/README.org#formatting

**Comment by kaushalmodi** [comment]
@wallyqs Copying you as I see that the original author is not active on GitHub any more. I am concerned seeing that this repo hasn't been updated in last 3 years, and 2 PR's (@pierre-lecocq) have been sitting in queue for 5 months. 

Can the repo have multiple authors, or can it be made an organization?

**Comment by wallyqs** [comment]
Hi @kaushalmodi if you send PR against this repo, I can take a look at merging it 
and cutting a new gem release with the change:
https://github.com/wallyqs/org-ruby/

**Comment by kaushalmodi** [comment]
@wallyqs I wish I could, but I haven't ever coded in Ruby, or have the Ruby/Gem dependencies installed on my system.

**Comment by kaushalmodi** [comment]
@wallyqs Thanks for your reply too! I missed the note on the README:

> Note: The project has moved. Further development is done at wallyqs/org-ruby Thanks Brian!

---

I'll move this issue to your repo. Thanks! Hopefully you or other Ruby coder can tackle it.

---

**Update**: [Moved][1]

[1]: https://github.com/wallyqs/org-ruby/issues/45

**Comment by kaushalmodi** [comment]
M

**Comment by wallyqs** [comment]
Thanks for following up! I seem to have missed the notifications against this repo somehow and now noticed there are a number of new issues, I will merge the pending PRs and cut a new release soon.
