### ISSUE TITLE
Support angle-links

### ISSUE THREAD

**Issue by punchagan** [bdewey/org-ruby#8]
Org-mode supports angle links like http://google.com. Can support for the same be added to org-ruby? 

Thanks.

**Comment by punchagan** [comment]
I mean angle links like `<http://google.com>`.

**Comment by Neil-Smithline** [comment]
Just want to double-check that I understand the problem. The difference I see is that in Org Mode, the angle brackets are part of the visual text of the link but are not part of the URL so clicking on an angle bracket will take you to the link. But in org-ruby, the angle brackets are not part of the text of the link so clicking on an angle bracket won't take you to the link.

**Comment by wallyqs** [comment]
This was added on: https://github.com/bdewey/org-ruby/commit/48e7bd97423f2501dc2d44e096d91ab5677e5c29
Angle links are supported starting from version 0.6.2 in rubygems.
Cheers!
